# Generated by Django 5.0.6 on 2024-07-01 07:42

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=100)),
                ('special', tinymce.models.HTMLField()),
                ('until', models.TextField()),
            ],
        ),
    ]
